### ISSUE TITLE
SSLError issue when have a test in lab chart

### ISSUE THREAD

**Issue by Kelukin** [odpi/egeria-charts#155]
When I deployed a lab chart and ran common/environment-check.ipynb in the Jupyter, I triggered the following Exceptions:

```
Checking OMAG Server Platform availability...
Exception: HTTPSConnectionPool(host='lab-core', port=9443): Max retries exceeded with url: /open-metadata/platform-services/users/garygeeke/server-platform/origin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
    Core Platform is down - start it before proceeding
Exception: HTTPSConnectionPool(host='lab-datalake', port=9443): Max retries exceeded with url: /open-metadata/platform-services/users/garygeeke/server-platform/origin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
    Data Lake Platform is down - start it before proceeding
Exception: HTTPSConnectionPool(host='lab-dev', port=9443): Max retries exceeded with url: /open-metadata/platform-services/users/garygeeke/server-platform/origin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
    Dev Platform is down - start it before proceeding
Done.
```

I am unsure whether the cause is the unalignment between the Jupyter and Egeria's version since you specify the Jupyter tag to the latest and have just upgraded Jupyter to 3.10-SNAPSHOT.

**Comment by planetf1** [comment]
I presume you installed the 3.9 version of the odpi-egeria-lab chart ie the latest one:
```
➜  ~ helm  search repo lab
NAME                    CHART VERSION   APP VERSION     DESCRIPTION           
egeria/odpi-egeria-lab  3.9.0           3.9             Egeria lab environment
```

Did this work as-is?

You also mentioned you'd updated Jupiter to 3.10-SNAPSHOT. This image is based on a core Jupyter image upon which we've added our notebooks - nothing else.

As such it would probably work just fine, unless there are changes in egeria that make it incompatible. That's very unlikely, though it's not something we'd test.

If you're having issues in reaching the egeria platforms (which is what the errors you are seeing suggest), the first thing I'd check is that those pods are running ie with:
```
kubectl get pods
kubectl get services
```

If they are not you could also try
```
kubectl describe pod <podid>
```
It may be the pod is not starting due to an error - could be related to security for example, or resource constraint.

What is your k8s host environment?

**Comment by planetf1** [comment]
In my first reply I missed one of your points - presuming you had modified your values.

As you point out, the values.yaml for that chart does indeed use 'latest' for the tag of the jupyter image.

I think we should change that back to be aligned to the release - I see it as a bug and will fix.

You can override the value locally via

```
helm install lab egeria/odpi-egeria-lab --set-string image.jupyter.tag=3.9
```

I'll check this out tomorrow, though I expect the reason your environment isn't working is different

**Comment by Kelukin** [comment]
> In my first reply I missed one of your points - presuming you had modified your values.
> 
> As you point out, the values.yaml for that chart does indeed use 'latest' for the tag of the jupyter image.
> 
> I think we should change that back to be aligned to the release - I see it as a bug and will fix.
> 
> You can override the value locally via
> 
> ```
> helm install lab egeria/odpi-egeria-lab --set-string image.jupyter.tag=3.9
> ```
> 
> I'll check this out tomorrow, though I expect the reason your environment isn't working is different

Thank you, @planetf1, for your quick reply. When I override the jupyter tag to the 3.9, it works without the SSL Error issue.

**Comment by Kelukin** [comment]
When I set the Jupyter's tag to the default value, the `latest`, this SSL Error issue comes out again. I deployed the lab chart in the Azure Kubernetes Service. 

It is quite strange, since all the services are in the running status. Besides that, this failed deployment and the above success deployment with specific Jupyter tag happen in one AKS.

**Comment by planetf1** [comment]
Using the 'master' version of the containers with the latest charts now works ok ie:
```
helm install lab egeria/odpi-egeria-lab --set-string egeria.version=3.10-SNAPSHOT
```

Following the PR above, which pinned the Jupyter version to the same we previously used - ie before some ssl and python library changes.

Will revisit this when we refactor the notebooks & get rid of our customized container (hopefully) - within next few months.

Thanks for the report. I think all the changes are made now so will close.

**Comment by planetf1** [comment]
If you get any further issues on Azure let us know.

**Comment by Kelukin** [comment]
Thank you, @planetf1! 
Everything looks fine now.

**Comment by planetf1** [comment]
I'm going to re-open this, as this problem still occurs when trying to run the notebooks locally.

However any fix will be rolled into the proposed changes to migrate notebooks to their own repository, and use a stock image

We should also ensure docs on running locally are updated at the same time

Re-opening and moving to base (since the charts are no longer affected since a workaround has been implemented)
